DO $$
DECLARE db text := current_database();
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rls_tester') THEN
    CREATE ROLE rls_tester LOGIN PASSWORD 'rls_tester_pw' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
  END IF;

  -- CONNECT auf „aktuelle DB“ dynamisch vergeben
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO rls_tester', db);

  GRANT USAGE ON SCHEMA public TO rls_tester;
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO rls_tester;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rls_tester;

  GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO rls_tester;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO rls_tester;
END $$;