name: ci
on:
  push:
  pull_request:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack & set pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.15.9 --activate
          pnpm -v

      - name: Install deps
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Lint
        run: pnpm -r --if-present run lint

      - name: Test
        run: pnpm -r --if-present run test

      - name: Build backend
        run: pnpm --filter @credity/backend run build
